name: Test

on: [push, pull_request]

jobs:
  attempt-1:
    uses: ./.github/workflows/_run-e2e-tests.yml
    with:
      attempt: "1"
    secrets: inherit

  attempt-2:
    needs: attempt-1
    if: needs.attempt-1.result == 'failure'
    uses: ./.github/workflows/_run-e2e-tests.yml
    with:
      attempt: "2"
    secrets: inherit

  attempt-3:
    needs: attempt-2
    if: needs.attempt-2.result == 'failure'
    uses: ./.github/workflows/_run-e2e-tests.yml
    with:
      attempt: "3"
      notify_on_failure: "true"
    secrets: inherit
